// 日本語翻訳マッピング

// ===== ポケモン名 =====
export const POKEMON_JA: Record<string, string> = {
  'Abomasnow': 'ユキノオー',
  'Alcremie': 'マホイップ',
  'Alomomola': 'ママンボウ',
  'Amoonguss': 'モロバレル',
  'Annihilape': 'コノヨザル',
  'Araquanid': 'オニシズクモ',
  'Arboliva': 'オリーヴァ',
  'Arcanine': 'ウインディ',
  'Arcanine-Hisui': 'ウインディ(ヒスイ)',
  'Archaludon': 'ブリジュラス',
  'Armarouge': 'グレンアルマ',
  'Azumarill': 'マリルリ',
  'Basculegion': 'イダイトウ',
  'Baxcalibur': 'セグレイブ',
  'Blaziken': 'バシャーモ',
  'Blissey': 'ハピナス',
  'Breloom': 'キノガッサ',
  'Brute Bonnet': 'アラブルタケ',
  'Bruxish': 'ハギギシリ',
  'Calyrex-Ice': 'バドレックス(白馬)',
  'Calyrex-Shadow': 'バドレックス(黒馬)',
  'Carbink': 'メレシー',
  'Ceruledge': 'ソウブレイズ',
  'Chandelure': 'シャンデラ',
  'Chansey': 'ラッキー',
  'Charizard': 'リザードン',
  'Chi-Yu': 'イーユイ',
  'Chien-Pao': 'パオジアン',
  'Cinccino': 'チラチーノ',
  'Clefable': 'ピクシー',
  'Clefairy': 'ピッピ',
  'Clodsire': 'ドオー',
  'Cloyster': 'パルシェン',
  'Comfey': 'キュワワー',
  'Corviknight': 'アーマーガア',
  'Cramorant': 'ウッウ',
  'Cresselia': 'クレセリア',
  'Dialga': 'ディアルガ',
  'Dialga-Origin': 'ディアルガ(オリジン)',
  'Ditto': 'メタモン',
  'Dondozo': 'ヘイラッシャ',
  'Donphan': 'ドンファン',
  'Dragapult': 'ドラパルト',
  'Dragonite': 'カイリュー',
  'Drifblim': 'フワライド',
  'Dugtrio': 'ダグトリオ',
  'Emboar': 'エンブオー',
  'Entei': 'エンテイ',
  'Espathra': 'クエスパトラ',
  'Espeon': 'エーフィ',
  'Eternatus': 'ムゲンダイナ',
  'Excadrill': 'ドリュウズ',
  'Farigiraf': 'リキキリン',
  'Feraligatr': 'オーダイル',
  'Fezandipiti': 'キチキギス',
  'Flamigo': 'カラミンゴ',
  'Flutter Mane': 'ハバタクカミ',
  'Forretress': 'フォレトス',
  'Froslass': 'ユキメノコ',
  'Frosmoth': 'モスノウ',
  'Gallade': 'エルレイド',
  'Garchomp': 'ガブリアス',
  'Gardevoir': 'サーナイト',
  'Garganacl': 'キョジオーン',
  'Gastrodon': 'トリトドン',
  'Gengar': 'ゲンガー',
  'Gholdengo': 'サーフゴー',
  'Giratina': 'ギラティナ',
  'Giratina-Origin': 'ギラティナ(オリジン)',
  'Glimmora': 'キラフロル',
  'Gliscor': 'グライオン',
  'Goodra': 'ヌメルゴン',
  'Gothitelle': 'ゴチルゼル',
  'Gouging Fire': 'ウガツホムラ',
  'Grafaiai': 'タギングル',
  'Great Tusk': 'イダイナキバ',
  'Greninja': 'ゲッコウガ',
  'Grimmsnarl': 'オーロンゲ',
  'Groudon': 'グラードン',
  'Gyarados': 'ギャラドス',
  'Hatterene': 'ブリムオン',
  'Heatran': 'ヒードラン',
  'Hippowdon': 'カバルドン',
  'Hitmontop': 'カポエラー',
  'Ho-Oh': 'ホウオウ',
  'Illumise': 'イルミーゼ',
  'Incineroar': 'ガオガエン',
  'Indeedee': 'イエッサン♂',
  'Indeedee-F': 'イエッサン♀',
  'Iron Bundle': 'テツノツツミ',
  'Iron Crown': 'テツノイワオ',
  'Iron Hands': 'テツノカイナ',
  'Iron Jugulis': 'テツノコウベ',
  'Iron Moth': 'テツノドクガ',
  'Iron Treads': 'テツノワダチ',
  'Iron Valiant': 'テツノブジン',
  'Jumpluff': 'ワタッコ',
  'Kangaskhan': 'ガルーラ',
  'Kingambit': 'ドドゲザン',
  'Kleavor': 'バサギリ',
  'Klefki': 'クレッフィ',
  'Koraidon': 'コライドン',
  'Kyogre': 'カイオーガ',
  'Kyurem': 'キュレム',
  'Kyurem-Black': 'キュレム(ブラック)',
  'Kyurem-White': 'キュレム(ホワイト)',
  'Landorus': 'ランドロス(化身)',
  'Landorus-Therian': 'ランドロス(霊獣)',
  'Latias': 'ラティアス',
  'Latios': 'ラティオス',
  'Lilligant-Hisui': 'ドレディア(ヒスイ)',
  'Lucario': 'ルカリオ',
  'Lugia': 'ルギア',
  'Lumineon': 'ネオラント',
  'Lunala': 'ルナアーラ',
  'Magnezone': 'ジバコイル',
  'Mamoswine': 'マンムー',
  'Maushold': 'イッカネズミ',
  'Meganium': 'メガニウム',
  'Meowscarada': 'マスカーニャ',
  'Meowstic': 'ニャオニクス',
  'Metagross': 'メタグロス',
  'Mewtwo': 'ミュウツー',
  'Mienshao': 'コジョンド',
  'Milotic': 'ミロカロス',
  'Mimikyu': 'ミミッキュ',
  'Miraidon': 'ミライドン',
  'Moltres-Galar': 'ファイヤー(ガラル)',
  'Muk-Alola': 'ベトベトン(アローラ)',
  'Murkrow': 'ヤミカラス',
  'Necrozma': 'ネクロズマ',
  'Necrozma-Dawn-Wings': 'ネクロズマ(あかつき)',
  'Necrozma-Dusk-Mane': 'ネクロズマ(たそがれ)',
  'Ninetales-Alola': 'キュウコン(アローラ)',
  'Ogerpon': 'オーガポン',
  'Okidogi': 'イイネイヌ',
  'Oranguru': 'ヤレユータン',
  'Overqwil': 'ハリーマン',
  'Pawmot': 'パーモット',
  'Pelipper': 'ペリッパー',
  'Porygon2': 'ポリゴン2',
  'Primarina': 'アシレーヌ',
  'Quaquaval': 'ウェーニバル',
  'Raging Bolt': 'タケルライコ',
  'Raichu': 'ライチュウ',
  'Raichu-Alola': 'ライチュウ(アローラ)',
  'Rayquaza': 'レックウザ',
  'Regidrago': 'レジドラゴ',
  'Regieleki': 'レジエレキ',
  'Regigigas': 'レジギガス',
  'Reshiram': 'レシラム',
  'Reuniclus': 'ランクルス',
  'Rhydon': 'サイドン',
  'Rhyperior': 'ドサイドン',
  'Ribombee': 'アブリボン',
  'Rillaboom': 'ゴリランダー',
  'Roaring Moon': 'トドロクツキ',
  'Rotom': 'ロトム',
  'Rotom-Wash': 'ロトム(ウォッシュ)',
  'Sableye': 'ヤミラミ',
  'Salazzle': 'エンニュート',
  'Samurott-Hisui': 'ダイケンキ(ヒスイ)',
  'Scizor': 'ハッサム',
  'Scraggy': 'ズルッグ',
  'Scream Tail': 'サケブシッポ',
  'Serperior': 'ジャローダ',
  'Shiftry': 'ダーテング',
  'Sinistcha': 'ヤバソチャ',
  'Skarmory': 'エアームド',
  'Skeledirge': 'ラウドボーン',
  'Slowking-Galar': 'ヤドキング(ガラル)',
  'Smeargle': 'ドーブル',
  'Sneasler': 'オオニューラ',
  'Snorlax': 'カビゴン',
  'Solgaleo': 'ソルガレオ',
  'Swampert': 'ラグラージ',
  'Sylveon': 'ニンフィア',
  'Talonflame': 'ファイアロー',
  'Tatsugiri': 'シャリタツ',
  'Terapagos': 'テラパゴス',
  'Thundurus': 'ボルトロス(化身)',
  'Thundurus-Therian': 'ボルトロス(霊獣)',
  'Ting-Lu': 'ディンルー',
  'Tinkaton': 'デカヌチャン',
  'Torkoal': 'コータス',
  'Tornadus': 'トルネロス(化身)',
  'Tornadus-Therian': 'トルネロス(霊獣)',
  'Toxapex': 'ドヒドイデ',
  'Tsareena': 'アマージョ',
  'Typhlosion-Hisui': 'バクフーン(ヒスイ)',
  'Tyranitar': 'バンギラス',
  'Umbreon': 'ブラッキー',
  'Ursaluna': 'ガチグマ',
  'Ursaluna-Bloodmoon': 'ガチグマ(赫月)',
  'Urshifu': 'ウーラオス(いちげき)',
  'Urshifu-Rapid-Strike': 'ウーラオス(れんげき)',
  'Venusaur': 'フシギバナ',
  'Volcarona': 'ウルガモス',
  'Walking Wake': 'ウネルミナモ',
  'Weezing': 'マタドガス',
  'Weezing-Galar': 'マタドガス(ガラル)',
  'Whimsicott': 'エルフーン',
  'Wo-Chien': 'チオンジェン',
  'Zacian': 'ザシアン',
  'Zamazenta': 'ザマゼンタ',
  'Zapdos': 'サンダー',
  'Zapdos-Galar': 'サンダー(ガラル)',
  'Zoroark-Hisui': 'ゾロアーク(ヒスイ)',
};

// ===== 技名 =====
export const MOVE_JA: Record<string, string> = {
  'Earthquake': 'じしん',
  'Close Combat': 'インファイト',
  'Flare Blitz': 'フレアドライブ',
  'Bullet Punch': 'バレットパンチ',
  'Shadow Claw': 'シャドークロー',
  'Dragon Claw': 'ドラゴンクロー',
  'Iron Head': 'アイアンヘッド',
  'Moonblast': 'ムーンフォース',
  'Psychic': 'サイコキネシス',
  'Flamethrower': 'かえんほうしゃ',
  'Ice Beam': 'れいとうビーム',
  'Thunderbolt': '10まんボルト',
  'Surf': 'なみのり',
  'Energy Ball': 'エナジーボール',
  'Draco Meteor': 'りゅうせいぐん',
  'Stone Edge': 'ストーンエッジ',
  'Knock Off': 'はたきおとす',
  'U-turn': 'とんぼがえり',
  'Protect': 'まもる',
  'Swords Dance': 'つるぎのまい',
  'Dragon Dance': 'りゅうのまい',
  'Foul Play': 'イカサマ',
  'Body Press': 'ボディプレス',
  'Psyshock': 'サイコショック',
  'Facade': 'からげんき',
  'Acrobatics': 'アクロバット',
  'Hex': 'たたりめ',
  'Brave Bird': 'ブレイブバード',
  'Giga Drain': 'ギガドレイン',
  'Rock Slide': 'いわなだれ',
  'Heat Wave': 'ねっぷう',
  'Hyper Voice': 'ハイパーボイス',
  'Icicle Spear': 'つららばり',
  'Aura Sphere': 'はどうだん',
  'Solar Beam': 'ソーラービーム',
  'Crunch': 'かみくだく',
  'Dark Pulse': 'あくのはどう',
  'Sucker Punch': 'ふいうち',
  'Return': 'おんがえし',
};

// ===== アイテム名 =====
export const ITEM_JA: Record<string, string> = {
  // 戦闘アイテム
  'Choice Band': 'こだわりハチマキ',
  'Choice Specs': 'こだわりメガネ',
  'Choice Scarf': 'こだわりスカーフ',
  'Life Orb': 'いのちのたま',
  'Expert Belt': 'たつじんのおび',
  'Assault Vest': 'とつげきチョッキ',
  'Eviolite': 'しんかのきせき',
  'Leftovers': 'たべのこし',
  'Rocky Helmet': 'ゴツゴツメット',
  'Focus Sash': 'きあいのタスキ',
  'Clear Amulet': 'クリアチャーム',
  'Covert Cloak': 'おんみつマント',
  'Safety Goggles': 'ぼうじんゴーグル',
  'Weakness Policy': 'じゃくてんほけん',
  'Booster Energy': 'ブーストエナジー',
  'Toxic Orb': 'どくどくだま',
  'Flame Orb': 'かえんだま',
  'Mental Herb': 'メンタルハーブ',
  'Light Clay': 'ひかりのねんど',
  'Loaded Dice': 'いかさまダイス',
  'Scope Lens': 'ピントレンズ',
  'Throat Spray': 'のどスプレー',
  'Protective Pads': 'ぼうごパッド',
  'Shed Shell': 'きれいなぬけがら',
  'Wide Lens': 'こうかくレンズ',
  // タイプ強化
  'Charcoal': 'もくたん',
  'Mystic Water': 'しんぴのしずく',
  'Miracle Seed': 'きせきのタネ',
  'Magnet': 'じしゃく',
  'Never-Melt Ice': 'とけないこおり',
  'Dragon Fang': 'りゅうのキバ',
  'Black Belt': 'くろおび',
  'Silk Scarf': 'シルクのスカーフ',
  'Poison Barb': 'どくバリ',
  'Soft Sand': 'やわらかいすな',
  'Sharp Beak': 'するどいくちばし',
  'Twisted Spoon': 'まがったスプーン',
  'Silver Powder': 'ぎんのこな',
  'Hard Stone': 'かたいいし',
  'Spell Tag': 'のろいのおふだ',
  'Black Glasses': 'くろいメガネ',
  'Metal Coat': 'メタルコート',
  'Fairy Feather': 'フェアリーフェザー',
  // 半減きのみ
  'Occa Berry': 'オッカのみ',
  'Passho Berry': 'イトケのみ',
  'Wacan Berry': 'ソクノのみ',
  'Rindo Berry': 'リンドのみ',
  'Yache Berry': 'ヤチェのみ',
  'Chople Berry': 'ヨプのみ',
  'Kebia Berry': 'ケビアのみ',
  'Shuca Berry': 'シュカのみ',
  'Coba Berry': 'バコウのみ',
  'Payapa Berry': 'ウタンのみ',
  'Tanga Berry': 'タンガのみ',
  'Charti Berry': 'ヨロギのみ',
  'Kasib Berry': 'カシブのみ',
  'Haban Berry': 'ハバンのみ',
  'Colbur Berry': 'ナモのみ',
  'Babiri Berry': 'ホズのみ',
  'Roseli Berry': 'ロゼルのみ',
  // 回復きのみ
  'Sitrus Berry': 'オボンのみ',
  'Lum Berry': 'ラムのみ',
  'Aguav Berry': 'ウイのみ',
  // メガストーン
  'Garchompite': 'ガブリアスナイト',
  'Metagrossite': 'メタグロスナイト',
  'Kangaskhanite': 'ガルーラナイト',
  'Tyranitarite': 'バンギラスナイト',
  'Scizorite': 'ハッサムナイト',
  'Lucarionite': 'ルカリオナイト',
  'Gardevoirite': 'サーナイトナイト',
  'Charizardite Y': 'リザードナイトY',
  'Meganiumite': 'メガニウムナイト',
  'Feraligatrite': 'オーダイルナイト',
  'Emboarite': 'エンブオーナイト',
  'Froslassite': 'ユキメノコナイト',
  'Dragonitite': 'カイリューナイト',
  'Abomasite': 'ユキノオーナイト',
};

// ===== 特性名 =====
export const ABILITY_JA: Record<string, string> = {
  'Adaptability': 'てきおうりょく',
  'Aftermath': 'ゆうばく',
  'Air Lock': 'エアロック',
  'Analytic': 'アナライズ',
  'Anticipation': 'きけんよち',
  'Arena Trap': 'ありじごく',
  'Armor Tail': 'テイルアーマー',
  'Aroma Veil': 'アロマベール',
  'As One Glastrier': 'じんばいったい',
  'As One Spectrier': 'じんばいったい',
  'Aura Break': 'オーラブレイク',
  'Battery': 'バッテリー',
  'Beads of Ruin': 'わざわいのたま',
  'Berserk': 'ぎゃくじょう',
  'Blaze': 'もうか',
  'Bulletproof': 'ぼうだん',
  'Cheek Pouch': 'ほおぶくろ',
  'Chlorophyll': 'ようりょくそ',
  'Clear Body': 'クリアボディ',
  'Commander': 'しれいとう',
  'Competitive': 'かちき',
  'Contrary': 'あまのじゃく',
  'Corrosion': 'ふしょく',
  'Costar': 'きょうえん',
  'Cud Chew': 'はんすう',
  'Curious Medicine': 'きみょうなくすり',
  'Cursed Body': 'のろわれボディ',
  'Cute Charm': 'メロメロボディ',
  'Damp': 'しめりけ',
  'Dark Aura': 'ダークオーラ',
  'Dauntless Shield': 'ふくつのたて',
  'Dazzling': 'ビビッドボディ',
  'Defiant': 'まけんき',
  'Disguise': 'ばけのかわ',
  'Download': 'ダウンロード',
  'Dragonize': 'ドラゴナイズ',
  'Dragons Maw': 'りゅうのあぎと',
  'Drizzle': 'あめふらし',
  'Drought': 'ひでり',
  'Early Bird': 'はやおき',
  'Effect Spore': 'ほうし',
  'Fairy Aura': 'フェアリーオーラ',
  'Filter': 'フィルター',
  'Flame Body': 'ほのおのからだ',
  'Flare Boost': 'ねつぼうそう',
  'Flash Fire': 'もらいび',
  'Flower Gift': 'フラワーギフト',
  'Flower Veil': 'フラワーベール',
  'Fluffy': 'もふもふ',
  'Friend Guard': 'フレンドガード',
  'Frisk': 'おみとおし',
  'Full Metal Body': 'メタルプロテクト',
  'Gale Wings': 'はやてのつばさ',
  'Gluttony': 'くいしんぼう',
  'Good As Gold': 'おうごんのからだ',
  'Gooey': 'ぬめぬめ',
  'Gorilla Tactics': 'ごりむちゅう',
  'Grass Pelt': 'くさのけがわ',
  'Grassy Surge': 'グラスメイカー',
  'Guard Dog': 'ばんけん',
  'Gulp Missile': 'うのミサイル',
  'Guts': 'こんじょう',
  'Hadron Engine': 'ハドロンエンジン',
  'Harvest': 'しゅうかく',
  'Healer': 'いやしのこころ',
  'Heatproof': 'たいねつ',
  'Honey Gather': 'みつあつめ',
  'Hospitality': 'おもてなし',
  'Huge Power': 'ちからもち',
  'Hustle': 'はりきり',
  'Hydration': 'うるおいボディ',
  'Hyper Cutter': 'かいりきバサミ',
  'Ice Body': 'アイスボディ',
  'Ice Scales': 'こおりのりんぷん',
  'Illusion': 'イリュージョン',
  'Immunity': 'めんえき',
  'Imposter': 'かわりもの',
  'Infiltrator': 'すりぬけ',
  'Inner Focus': 'せいしんりょく',
  'Insomnia': 'ふみん',
  'Intimidate': 'いかく',
  'Intrepid Sword': 'ふとうのけん',
  'Iron Fist': 'てつのこぶし',
  'Justified': 'せいぎのこころ',
  'Keen Eye': 'するどいめ',
  'Leaf Guard': 'リーフガード',
  'Levitate': 'ふゆう',
  'Light Metal': 'ライトメタル',
  'Lightning Rod': 'ひらいしん',
  'Limber': 'じゅうなん',
  'Liquid Voice': 'うるおいボイス',
  'Magic Bounce': 'マジックミラー',
  'Magic Guard': 'マジックガード',
  'Magician': 'マジシャン',
  'Magnet Pull': 'じりょく',
  'Marvel Scale': 'ふしぎなうろこ',
  'Mega Launcher': 'メガランチャー',
  'Mega Sol': 'メガソル',
  'Merciless': 'ひとでなし',
  'Minds Eye': 'しんがん',
  'Mirror Armor': 'ミラーアーマー',
  'Misty Surge': 'ミストメイカー',
  'Mold Breaker': 'かたやぶり',
  'Moody': 'ムラっけ',
  'Moxie': 'じしんかじょう',
  'Multiscale': 'マルチスケイル',
  'Natural Cure': 'しぜんかいふく',
  'Neuroforce': 'ブレインフォース',
  'Neutralizing Gas': 'かがくへんかガス',
  'Oblivious': 'どんかん',
  'Opportunist': 'びんじょう',
  'Orichalcum Pulse': 'ひひいろのこどう',
  'Overcoat': 'ぼうじん',
  'Overgrow': 'しんりょく',
  'Own Tempo': 'マイペース',
  'Parental Bond': 'おやこあい',
  'Pickpocket': 'わるいてぐせ',
  'Pixilate': 'フェアリースキン',
  'Poison Heal': 'ポイズンヒール',
  'Poison Point': 'どくのトゲ',
  'Poison Touch': 'どくしゅ',
  'Power Of Alchemy': 'かがくのちから',
  'Power Spot': 'パワースポット',
  'Prankster': 'いたずらごころ',
  'Pressure': 'プレッシャー',
  'Prism Armor': 'プリズムアーマー',
  'Protean': 'へんげんじざい',
  'Protosynthesis': 'こだいかっせい',
  'Psychic Surge': 'サイコメイカー',
  'Punk Rock': 'パンクロック',
  'Pure Power': 'ヨガパワー',
  'Purifying Salt': 'きよめのしお',
  'Quark Drive': 'クォークチャージ',
  'Queenly Majesty': 'じょおうのいげん',
  'Rain Dish': 'あめうけざら',
  'Reckless': 'すてみ',
  'Regenerator': 'さいせいりょく',
  'Rock Head': 'いしあたま',
  'Rough Skin': 'さめはだ',
  'Sand Force': 'すなのちから',
  'Sand Rush': 'すなかき',
  'Sand Stream': 'すなおこし',
  'Sand Veil': 'すながくれ',
  'Sap Sipper': 'そうしょく',
  'Scrappy': 'きもったま',
  'Seed Sower': 'たねまき',
  'Serene Grace': 'てんのめぐみ',
  'Shadow Shield': 'ファントムガード',
  'Shadow Tag': 'かげふみ',
  'Sharpness': 'きれあじ',
  'Shed Skin': 'だっぴ',
  'Sheer Force': 'ちからずく',
  'Shell Armor': 'シェルアーマー',
  'Shield Dust': 'りんぷん',
  'Skill Link': 'スキルリンク',
  'Slow Start': 'スロースタート',
  'Sniper': 'スナイパー',
  'Snow Cloak': 'ゆきがくれ',
  'Snow Warning': 'ゆきふらし',
  'Solar Power': 'サンパワー',
  'Solid Rock': 'ハードロック',
  'Soundproof': 'ぼうおん',
  'Speed Boost': 'かそく',
  'Stall': 'あとだし',
  'Stalwart': 'すじがねいり',
  'Stamina': 'じきゅうりょく',
  'Static': 'せいでんき',
  'Steadfast': 'ふくつのこころ',
  'Steely Spirit': 'はがねのせいしん',
  'Stench': 'あくしゅう',
  'Sticky Hold': 'ねんちゃく',
  'Storm Drain': 'よびみず',
  'Strong Jaw': 'がんじょうあご',
  'Sturdy': 'がんじょう',
  'Super Luck': 'きょううん',
  'Supreme Overlord': 'そうだいしょう',
  'Surge Surfer': 'サーフテール',
  'Swarm': 'むしのしらせ',
  'Sweet Veil': 'スイートベール',
  'Swift Swim': 'すいすい',
  'Sword of Ruin': 'わざわいのつるぎ',
  'Symbiosis': 'きょうせい',
  'Synchronize': 'シンクロ',
  'Tablets of Ruin': 'わざわいのおふだ',
  'Tangled Feet': 'ちどりあし',
  'Technician': 'テクニシャン',
  'Telepathy': 'テレパシー',
  'Tera Shift': 'テラスチェンジ',
  'Teravolt': 'テラボルテージ',
  'Thermal Exchange': 'ねつこうかん',
  'Thick Fat': 'あついしぼう',
  'Tinted Lens': 'いろめがね',
  'Torrent': 'げきりゅう',
  'Tough Claws': 'かたいツメ',
  'Toxic Chain': 'どくのくさり',
  'Toxic Debris': 'どくげしょう',
  'Trace': 'トレース',
  'Transistor': 'トランジスタ',
  'Triage': 'ヒーリングシフト',
  'Turboblaze': 'ターボブレイズ',
  'Unaware': 'てんねん',
  'Unburden': 'かるわざ',
  'Unnerve': 'きんちょうかん',
  'Unseen Fist': 'ふかしのこぶし',
  'Vessel of Ruin': 'わざわいのうつわ',
  'Vital Spirit': 'やるき',
  'Volt Absorb': 'ちくでん',
  'Water Absorb': 'ちょすい',
  'Water Bubble': 'すいほう',
  'Water Veil': 'みずのベール',
  'Weak Armor': 'くだけるよろい',
  'White Smoke': 'しろいけむり',
  'Wind Rider': 'かぜのり',
  'Wonder Skin': 'ミラクルスキン',
};

// ===== タイプ名 =====
export const TYPE_JA: Record<string, string> = {
  'Normal': 'ノーマル',
  'Fire': 'ほのお',
  'Water': 'みず',
  'Electric': 'でんき',
  'Grass': 'くさ',
  'Ice': 'こおり',
  'Fighting': 'かくとう',
  'Poison': 'どく',
  'Ground': 'じめん',
  'Flying': 'ひこう',
  'Psychic': 'エスパー',
  'Bug': 'むし',
  'Rock': 'いわ',
  'Ghost': 'ゴースト',
  'Dragon': 'ドラゴン',
  'Dark': 'あく',
  'Steel': 'はがね',
  'Fairy': 'フェアリー',
  'Stellar': 'ステラ',
};

// ===== 性格名 =====
export const NATURE_JA: Record<string, string> = {
  'Hardy': 'がんばりや',
  'Lonely': 'さみしがり',
  'Brave': 'ゆうかん',
  'Adamant': 'いじっぱり',
  'Naughty': 'やんちゃ',
  'Bold': 'ずぶとい',
  'Docile': 'すなお',
  'Relaxed': 'のんき',
  'Impish': 'わんぱく',
  'Lax': 'のうてんき',
  'Timid': 'おくびょう',
  'Hasty': 'せっかち',
  'Serious': 'まじめ',
  'Jolly': 'ようき',
  'Naive': 'むじゃき',
  'Modest': 'ひかえめ',
  'Mild': 'おっとり',
  'Quiet': 'れいせい',
  'Bashful': 'てれや',
  'Rash': 'うっかりや',
  'Calm': 'おだやか',
  'Gentle': 'おとなしい',
  'Sassy': 'なまいき',
  'Careful': 'しんちょう',
  'Quirky': 'きまぐれ',
};

// ===== 天候 =====
export const WEATHER_JA: Record<string, string> = {
  'Sun': 'はれ',
  'Rain': 'あめ',
  'Sand': 'すなあらし',
  'Snow': 'ゆき',
  'Harsh Sunshine': 'おおひでり',
  'Heavy Rain': 'おおあめ',
  'Strong Winds': 'らんきりゅう',
};

// ===== テライン =====
export const TERRAIN_JA: Record<string, string> = {
  'Electric': 'エレキフィールド',
  'Grassy': 'グラスフィールド',
  'Psychic': 'サイコフィールド',
  'Misty': 'ミストフィールド',
};

// ===== ステータス名 =====
export const STAT_JA: Record<string, string> = {
  'hp': 'HP', 'atk': '攻撃', 'def': '防御',
  'spa': '特攻', 'spd': '特防', 'spe': '素早',
};

// ===== 状態異常 =====
export const STATUS_JA: Record<string, string> = {
  '': 'なし',
  'brn': 'やけど',
  'par': 'まひ',
  'psn': 'どく',
  'tox': 'もうどく',
  'slp': 'ねむり',
  'frz': 'こおり',
};

// ===== KOテキスト =====
export function koTextJa(chance: number, n: number): string {
  if (n === 0) return 'ダメージなし';
  const prefix = chance >= 1 ? '確定' : chance > 0 ? `乱数(${(chance * 100).toFixed(1)}%)` : '';
  if (!prefix) return `${n}発では倒せない`;
  return `${prefix}${n}発`;
}

export function koTextEn(chance: number, n: number): string {
  if (n === 0) return 'No damage';
  if (chance >= 1) return `Guaranteed ${n}HKO`;
  if (chance > 0) return `${(chance * 100).toFixed(1)}% chance to ${n}HKO`;
  return `Does not ${n}HKO`;
}

// ===== 相性テキスト =====
export function effectivenessTextJa(mult: number): string {
  if (mult === 0) return '効果なし (0x)';
  if (mult === 0.25) return 'ほとんど効かない (0.25x)';
  if (mult === 0.5) return '今ひとつ (0.5x)';
  if (mult === 1) return '';
  if (mult === 2) return '効果抜群 (2x)';
  if (mult === 4) return '効果抜群 (4x)';
  return `${mult}x`;
}

export function effectivenessTextEn(mult: number): string {
  if (mult === 0) return 'No effect (0x)';
  if (mult === 0.25) return 'Not very effective (0.25x)';
  if (mult === 0.5) return 'Not very effective (0.5x)';
  if (mult === 1) return '';
  if (mult === 2) return 'Super effective (2x)';
  if (mult === 4) return 'Super effective (4x)';
  return `${mult}x`;
}

// ===== ステータス名 (English) =====
export const STAT_EN: Record<string, string> = {
  'hp': 'HP', 'atk': 'Atk', 'def': 'Def',
  'spa': 'SpA', 'spd': 'SpD', 'spe': 'Spe',
};

// ===== 状態異常 (English) =====
export const STATUS_EN: Record<string, string> = {
  '': 'None',
  'brn': 'Burn',
  'par': 'Paralysis',
  'psn': 'Poison',
  'tox': 'Toxic',
  'slp': 'Sleep',
  'frz': 'Freeze',
};

// ===== 分類 (English) =====
export const CATEGORY_EN: Record<string, string> = { Physical: 'Physical', Special: 'Special', Status: 'Status' };
export const CATEGORY_JA: Record<string, string> = { Physical: '物理', Special: '特殊', Status: '変化' };

// ===== 汎用翻訳ヘルパー =====
import type { Lang } from './LangContext';

/** Returns Japanese or English display name based on lang. For 'en', returns the key itself. */
export function t(en: string, jaMap: Record<string, string>, lang: Lang): string {
  return lang === 'ja' ? (jaMap[en] ?? en) : en;
}

/** Legacy helper (always Japanese) */
export function ja(en: string, map: Record<string, string>): string {
  return map[en] ?? en;
}

// ===== UI文字列 =====
export const UI: Record<string, { ja: string; en: string }> = {
  title: { ja: 'Champions ダメージ計算機', en: 'Champions Damage Calculator' },
  attacker: { ja: '攻撃側', en: 'Attacker' },
  defender: { ja: '防御側', en: 'Defender' },
  pokemon: { ja: 'ポケモン', en: 'Pokemon' },
  nature: { ja: '性格', en: 'Nature' },
  ability: { ja: '特性', en: 'Ability' },
  item: { ja: 'もちもの', en: 'Item' },
  itemNone: { ja: 'なし', en: 'None' },
  mega: { ja: 'メガ', en: 'Mega' },
  teraType: { ja: 'テラスタイプ', en: 'Tera Type' },
  teraNone: { ja: 'なし', en: 'None' },
  teraActive: { ja: 'テラス中', en: 'Tera ON' },
  teraOff: { ja: 'テラスOFF', en: 'Tera OFF' },
  teraLabel: { ja: 'テラス', en: 'Tera' },
  sp: { ja: 'SP配分', en: 'SP Distribution' },
  spTotal: { ja: '合計', en: 'Total' },
  status: { ja: '状態異常', en: 'Status' },
  boosts: { ja: '能力ランク', en: 'Stat Boosts' },
  move: { ja: 'わざ', en: 'Move' },
  power: { ja: '威力', en: 'Power' },
  crit: { ja: '急所', en: 'Crit' },
  spread: { ja: '全体技', en: 'Spread' },
  singles: { ja: 'シングル', en: 'Singles' },
  doubles: { ja: 'ダブル', en: 'Doubles' },
  weatherNone: { ja: '天候なし', en: 'No Weather' },
  terrainNone: { ja: 'フィールドなし', en: 'No Terrain' },
  details: { ja: '詳細', en: 'Details' },
  close: { ja: '閉じる', en: 'Close' },
  atkSide: { ja: '攻撃側', en: 'Attacker Side' },
  defSide: { ja: '防御側', en: 'Defender Side' },
  fieldAbilities: { ja: 'フィールド特性', en: 'Field Abilities' },
  helpingHand: { ja: 'てだすけ', en: 'Helping Hand' },
  reflect: { ja: 'リフレクター', en: 'Reflect' },
  lightScreen: { ja: 'ひかりのかべ', en: 'Light Screen' },
  auroraVeil: { ja: 'オーロラベール', en: 'Aurora Veil' },
  battery: { ja: 'バッテリー', en: 'Battery' },
  powerSpot: { ja: 'パワースポット', en: 'Power Spot' },
  steelySpirit: { ja: 'はがねのせいしん', en: 'Steely Spirit' },
  flowerGift: { ja: 'フラワーギフト', en: 'Flower Gift' },
  friendGuard: { ja: 'フレンドガード', en: 'Friend Guard' },
  fairyAura: { ja: 'フェアリーオーラ', en: 'Fairy Aura' },
  darkAura: { ja: 'ダークオーラ', en: 'Dark Aura' },
  auraBreak: { ja: 'オーラブレイク', en: 'Aura Break' },
  beadsOfRuin: { ja: 'わざわいのたま', en: 'Beads of Ruin' },
  tabletsOfRuin: { ja: 'わざわいのおふだ', en: 'Tablets of Ruin' },
  swordOfRuin: { ja: 'わざわいのつるぎ', en: 'Sword of Ruin' },
  vesselOfRuin: { ja: 'わざわいのうつわ', en: 'Vessel of Ruin' },
  gravity: { ja: 'じゅうりょく', en: 'Gravity' },
  selectPrompt: { ja: 'ポケモンとわざを選択してください', en: 'Select a Pokemon and move' },
  showRolls: { ja: '16乱数を表示', en: 'Show 16 rolls' },
  hideRolls: { ja: '乱数を隠す', en: 'Hide rolls' },
  search: { ja: 'を検索...', en: 'Search...' },
  hp: { ja: 'HP', en: 'HP' },

  // パーティ関連
  party: { ja: 'パーティ', en: 'Party' },
  newParty: { ja: '新規パーティ', en: 'New Party' },
  partyName: { ja: 'パーティ名', en: 'Party Name' },
  addMember: { ja: 'メンバー追加', en: 'Add Member' },
  deleteMember: { ja: '削除', en: 'Delete' },
  setAttacker: { ja: '攻撃側に設定', en: 'Set as Attacker' },
  setDefender: { ja: '防御側に設定', en: 'Set as Defender' },
  exportShowdown: { ja: 'エクスポート', en: 'Export' },
  importShowdown: { ja: 'インポート', en: 'Import' },
  copied: { ja: 'コピーしました', en: 'Copied!' },
  moveSlot: { ja: '技', en: 'Move' },
  emptySlot: { ja: '空きスロット', en: 'Empty Slot' },
  deleteParty: { ja: 'パーティ削除', en: 'Delete Party' },
  fromParty: { ja: 'パーティから', en: 'From Party' },
  save: { ja: '保存', en: 'Save' },
  cancel: { ja: 'キャンセル', en: 'Cancel' },
  noParties: { ja: 'パーティがありません', en: 'No parties saved' },
};
