/**
 * Language helpers for the viewer.
 *
 * The JP dictionaries live in `home-data/storage/i18n/*.json` and are
 * generated by the build-*-ja.mjs scripts. Importing them statically lets
 * Vite bake them into the same bundle that `viteSingleFile()` then inlines
 * into `build/meta.html`, so no network fetch is required at runtime.
 *
 * Names that have no JP entry (e.g. brand-new forms scraped before the
 * dictionary catches up, or the synthetic "Other" long-tail bucket) fall
 * back to the original English string so the UI never renders blank cells.
 *
 * Every helper takes a `lang` argument so the same component tree can be
 * driven by the global language toggle without prop-drilling per-string
 * callbacks. Pass `"ja"` to get the Japanese form (with English fallback)
 * and `"en"` to keep the original English string.
 */

import pokemonJaJson from "../storage/i18n/pokemon-ja.json";
import movesJaJson from "../storage/i18n/moves-ja.json";
import abilitiesJaJson from "../storage/i18n/abilities-ja.json";
import itemsJaJson from "../storage/i18n/items-ja.json";

export type Lang = "ja" | "en";

const POKEMON_JA: Record<string, string> = pokemonJaJson as Record<
  string,
  string
>;

const MOVES_JA: Record<string, string> = movesJaJson as Record<string, string>;

const ABILITIES_JA: Record<string, string> = abilitiesJaJson as Record<
  string,
  string
>;

const ITEMS_JA: Record<string, string> = itemsJaJson as Record<string, string>;

/**
 * Pokemon type → JP translation. Used by TypeBadge and SE type displays.
 */
const TYPE_JA: Record<string, string> = {
  Normal: "ノーマル",
  Fire: "ほのお",
  Water: "みず",
  Electric: "でんき",
  Grass: "くさ",
  Ice: "こおり",
  Fighting: "かくとう",
  Poison: "どく",
  Ground: "じめん",
  Flying: "ひこう",
  Psychic: "エスパー",
  Bug: "むし",
  Rock: "いわ",
  Ghost: "ゴースト",
  Dragon: "ドラゴン",
  Dark: "あく",
  Steel: "はがね",
  Fairy: "フェアリー",
};

/**
 * Pokemon nature → JP translation. Pikalytics emits these in English
 * (e.g. "Relaxed", "Jolly") but Japanese players know them as のんき,
 * ようき, etc. Used by the "Top Build" section of <PokemonDetail />.
 */
const NATURE_JA: Record<string, string> = {
  Hardy: "がんばりや",
  Lonely: "さみしがり",
  Brave: "ゆうかん",
  Adamant: "いじっぱり",
  Naughty: "やんちゃ",
  Bold: "ずぶとい",
  Docile: "すなお",
  Relaxed: "のんき",
  Impish: "わんぱく",
  Lax: "のうてんき",
  Timid: "おくびょう",
  Hasty: "せっかち",
  Serious: "まじめ",
  Jolly: "ようき",
  Naive: "むじゃき",
  Modest: "ひかえめ",
  Mild: "おっとり",
  Quiet: "れいせい",
  Bashful: "てれや",
  Rash: "うっかりや",
  Calm: "おだやか",
  Gentle: "おとなしい",
  Sassy: "なまいき",
  Careful: "しんちょう",
  Quirky: "きまぐれ",
};

/** Internal helper: pick the JP entry from `dict` or fall back to `name`. */
function pick(dict: Record<string, string>, name: string, lang: Lang): string {
  if (lang === "en") return name;
  return dict[name] ?? name;
}

/**
 * Return the localized display name for a Pokemon. Falls back to the
 * English name when the JP dictionary has no entry.
 */
export function localizePokemon(name: string, lang: Lang = "ja"): string {
  return pick(POKEMON_JA, name, lang);
}

/**
 * Return both the JP and English forms joined for search-friendly text.
 * Used by the toolbar search box so users can type either language and
 * still hit the same row regardless of the active UI language.
 */
export function localizedSearchKey(name: string): string {
  const ja = POKEMON_JA[name];
  return ja ? `${name} ${ja}` : name;
}

/**
 * Return the localized display name for a move. Falls back to the English
 * name when the dictionary has no entry (e.g. the synthetic "Other"
 * long-tail bucket emitted by the merger).
 */
export function localizeMove(name: string, lang: Lang = "ja"): string {
  return pick(MOVES_JA, name, lang);
}

/** Translate a type name to JP (or echo back when lang is `en`). */
export function localizeType(name: string, lang: Lang = "ja"): string {
  return pick(TYPE_JA, name, lang);
}

/** Translate a single nature name to JP (or echo back when lang is `en`). */
export function localizeNature(name: string, lang: Lang = "ja"): string {
  return pick(NATURE_JA, name, lang);
}

/** Nature → boosted/lowered stat labels (HABCDS notation) */
const NATURE_MODS: Record<string, [string, string]> = {
  Adamant: ["A","C"], Jolly: ["S","C"], Modest: ["C","A"], Timid: ["S","A"],
  Bold: ["B","A"], Impish: ["B","C"], Calm: ["D","A"], Careful: ["D","C"],
  Brave: ["A","S"], Quiet: ["C","S"], Relaxed: ["B","S"], Sassy: ["D","S"],
  Lonely: ["A","B"], Hasty: ["S","B"], Mild: ["C","B"], Gentle: ["D","B"],
  Naughty: ["A","D"], Naive: ["S","D"], Rash: ["C","D"], Lax: ["B","D"],
};

/** Localized nature with +/- stat indicator, e.g. "いじっぱり (+A-C)" */
export function natureDisplay(name: string, lang: Lang = "ja"): string {
  const localized = localizeNature(name, lang);
  const mods = NATURE_MODS[name];
  if (!mods) return localized;
  return `${localized} (+${mods[0]}-${mods[1]})`;
}

/**
 * Return the localized display name for an ability. Falls back to the
 * English name when the dictionary has no entry.
 */
export function localizeAbility(name: string, lang: Lang = "ja"): string {
  return pick(ABILITIES_JA, name, lang);
}

/**
 * Return the localized display name for an item. Falls back to the
 * English name when the dictionary has no entry.
 */
export function localizeItem(name: string, lang: Lang = "ja"): string {
  return pick(ITEMS_JA, name, lang);
}

/**
 * Compare two Pokemon names for sorting. In JA mode, sorts by the
 * Japanese name in 五十音順 (gojuon order) using `String.localeCompare`
 * with locale `'ja'`. In EN mode, sorts alphabetically by the English name.
 *
 * Both `a` and `b` are canonical English names (the keys used throughout
 * the data layer). The function resolves them to their localized forms
 * before comparing.
 */
export function comparePokemonName(a: string, b: string, lang: Lang): number {
  if (lang === "ja") {
    const jaA = POKEMON_JA[a] ?? a;
    const jaB = POKEMON_JA[b] ?? b;
    return jaA.localeCompare(jaB, "ja");
  }
  return a.localeCompare(b, "en");
}

/**
 * Bilingual rendering helper used in the spread display. In JA mode it
 * returns "ようき (Jolly)"; in EN mode it returns "Jolly (ようき)".
 */
export function natureLabel(name: string, lang: Lang = "ja"): string {
  const ja = NATURE_JA[name];
  if (!ja) return name;
  return lang === "ja" ? `${ja} (${name})` : `${name} (${ja})`;
}
